// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrNRQ3pt-saqRJhHvxkptFc5fCtlOH8Kc',
    appId: '1:950541571844:web:ea6d54c3875299ac0b2251',
    messagingSenderId: '950541571844',
    projectId: 'logistica-cap',
    authDomain: 'logistica-cap.firebaseapp.com',
    storageBucket: 'logistica-cap.firebasestorage.app',
    measurementId: 'G-BCBN75S3EN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWZ1RKnIG5e5aaRM_2u6Lazn4sn6Ltav4',
    appId: '1:950541571844:android:a81f44c43e0314020b2251',
    messagingSenderId: '950541571844',
    projectId: 'logistica-cap',
    storageBucket: 'logistica-cap.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW1qzDnAGnwix2Iz7DE_2Gx0ztXqSedLI',
    appId: '1:950541571844:ios:141230e01b2f2a9f0b2251',
    messagingSenderId: '950541571844',
    projectId: 'logistica-cap',
    storageBucket: 'logistica-cap.firebasestorage.app',
    iosBundleId: 'com.example.logisticaCap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW1qzDnAGnwix2Iz7DE_2Gx0ztXqSedLI',
    appId: '1:950541571844:ios:141230e01b2f2a9f0b2251',
    messagingSenderId: '950541571844',
    projectId: 'logistica-cap',
    storageBucket: 'logistica-cap.firebasestorage.app',
    iosBundleId: 'com.example.logisticaCap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrNRQ3pt-saqRJhHvxkptFc5fCtlOH8Kc',
    appId: '1:950541571844:web:7b92cac7bcb028050b2251',
    messagingSenderId: '950541571844',
    projectId: 'logistica-cap',
    authDomain: 'logistica-cap.firebaseapp.com',
    storageBucket: 'logistica-cap.firebasestorage.app',
    measurementId: 'G-VVM0EET02Y',
  );

}